### ISSUE TITLE
Design block builder interface.

### ISSUE THREAD

**Issue by Will-Smith11** [SorellaLabs/angstrom#38]
### Reasoning
At launch and pre-launch we want to be able to have as many builders as possible easily integrate with our system in order to allow for the most composability  and proper pricing of storage slots as this will lead to more inclusion and a better experience for all users. 

### TODO
- [ ] Look at how current block builders function in order to gain scope on how to design this most optimally
- [ ] Indicate everywhere in the code base that this interfacing needs to occur and possible redesigning needs to occur in order to encapsulate functionality nicely
- [ ] Draw up in Gitbook the architecture of these additional details as well as traits for all interfaces between guards and block builders
