### ISSUE TITLE
feat: scope out chainbound integration

### ISSUE THREAD

**Issue by Will-Smith11** [SorellaLabs/angstrom#54]
We have a possible integration with chainbound for mempool and block data. However given that forkchoice for blocks in based off of the beacon node and the becaon node uses the slot clock for this. this may or may not be needed at all.
### TODO
- [ ] Fully understand what benfits chainbound can offer when it comes to block deliverance times
- [ ] Fully understand how the current CL and EL communicate all notifiy us of the canonical chain state transition
- [ ] Take action on the results if necessary
